### PR TITLE
replacement feature

### PR DESCRIPTION
**Pull request by munrocket**
Minifiers not works with strings

### CODE REVIEW

**Comment by TrySound** [comment]
This feature can be implemented as another plugin. This one does one thing - converts file content to module. All optimisations should be done by prior plugins.

**Comment by munrocket** [comment]
@TrySound do you have an example that works for all entire file or with exported strings only? I think this is good suggest. Feature with replace EOL should be out of the box.

**Comment by munrocket** [comment]
#8 basically the same

**Comment by munrocket** [comment]
@TrySound Ok, I replaced `\n` but I also want to remove spaces in my css and svg.

This problem don't have good solution without this PR or some similar improvement.

**Comment by munrocket** [comment]
Fuck. Replacement can't be in all bundle, it must be in this plugin.

**Pull request closed without merging**
