### PR TITLE
Add include and exclude filter.

### PR DESCRIPTION
**Pull request by differui**
```js
rollup.rollup({
    plugins: [
        string({ extensions: ['.tpl', '.html'], exclude: ['path/to/exclude'] }),
    ]
});
```

### CODE REVIEW

**Comment by TrySound** [comment]
@differui Hi. Thanks for pr. I would like to remove `extensions` option and make `include` required.

**Comment by differui** [comment]
@TrySound Hi. This plugin really useful.Thanks for you work.I am looking forward to updating.

**Comment by TrySound** [comment]
@differui Don't you know how to squash commits?

**Comment by differui** [comment]
@TrySound You mean `git rebase -i `?To squash what?

**Comment by TrySound** [comment]
@differui You could not close PR, but make some changes and squash commits.

**Pull request closed without merging**
